config/routes.rb
TaskApp::Application.routes.draw do

  get "/sessions/new" => 'sessions#new'

  post "/sessions" => 'sessions#create', :as => 'new_session'

  delete "/sessions" => 'sessions#destroy'

  root :to => 'sessions#new'

resources :users
resources :tasks
resources :teams
resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title

  belongs_to :team
  has_many :users, :through => :team
  has_many :tasks
end

app/models/roster.rb
class Roster < ActiveRecord::Base
  attr_accessible :team_id, :user_id

  belongs_to :user
  belongs_to :team 
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :description, :title, :user_id

  belongs_to :user 
  belongs_to :project
  
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :user_id

  after_create :add_to_roster

  belongs_to :user
  has_many :rosters
  has_many :users, :through => :rosters
  has_many :projects
  has_many :tasks, :through => :projects

  def add_to_roster
    @roster = Roster.new
    @roster.user_id = self.user_id
    @roster.team_id = self.id
    @roster.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :company, :email, :first_name, :last_name, :password

  has_secure_password
  has_many :rosters
  has_many :teams
  has_many :teams, :through => :rosters
  has_many :projects, :through => :teams
  has_many :tasks, :through => :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by_email(params[:email])

  	if user.present? && user.authenticate(params[:password])
  		session[:id] = user.id
  		redirect_to user_url(user), notice: 'Success!'
  	else
  		redirect_to :back, notice: 'Nope, not this time.'
  	end
  end

  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html {redirect_to tasks_url}
        format.js
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  def index
    @tasks = Task.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def new
    @team = Team.new

  end

  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html {redirect_to teams_url}
        format.js
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
    @teams = Team.all
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, except: [:new, :create, :index]
  before_filter :authorize_user, except: [:new, :create]


  def find_user
    @user = User.find(session[:id])
    
  end

  def authorize_user
    logger.info "session[:id] = #{session[:id]}"
    logger.info "session[:id].class = #{session[:id].class}"
    logger.info "params[:id] = #{params[:id]}"
    logger.info "params[:id.class] = #{params[:id].class}"

    if session[:id].to_s != params[:id]
      redirect_to root_url, notice: "Can't do that"
    end
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save 
        format.html { redirect_to root_url}
        format.js
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
  end

  def show
    @user = User.find(session[:id])
    @tasks = Task.where(:user_id => @user.id)
    @teams = Team.where(:user_id => @user.id).all
    @projects = @user.projects

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid"></br>
	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="#">Title</a>
	    <ul class="nav">
	      <li class="active"><%= link_to "Home", user_url(User.find(session[:id])) %></li>
	      <li><a href="#">Link</a></li>
	      <% if session[:id].present? %>
	      <li><%= link_to "Logout", '/sessions', method: 'delete' %></li>
	      <% else %>
	      <li><%= link_to "Login", '/sessions', method: 'post' %></li>
	      <% end %>
	    </ul>
	  </div>
	</div>
<%= yield %>
</div>
</body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<div class='row-fluid'>
	<div class='span8'>
		<h1>My Tasks</a></h1>
		<%= link_to 'create a new task', new_task_url, class: 'btn btn-success'  %></br></br>
		<div>
			<table class='table table-striped table-hover well'>
				<th></th><th>Task Name</th><th>Description</th>
				<% @tasks.each do |task| %>
					<%= render 'task_partial', task: task %>
				<% end %>
			</table>
		</div>

	</div>

	<div class='span4'>

	</div>
</div>

app/views/tasks/new.html.erb
<div class='row-fluid'>
	<div class='span4'>

	</div>
	<div class='span4 well'><center>
		<h2>Add a new task</h2>
		<%= form_for @task do |f| %>
			<%= f.text_field :title, placeholder: 'task name' %>
			<%= f.text_area :description, placeholder: 'task description', rows: '5' %></br>
			<%= f.submit 'Create task', class: 'btn btn-primary' %>
		<% end %>
	</center></div>
	<div class='span4'>

	</div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/_task_partial.html.erb
<tr>
	<td width="5%;"></td>
	<td><%= task.title %></td>
	<td><%= task.description %></td>
</tr>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class='row-fluid'>
	<div class='span12 well'>
		<center><h2>Start here.</h2>
		<%= form_for @user do |f| %>

			<%= f.text_field :first_name, placeholder: 'first name' %>
			<%= f.text_field :last_name, placeholder: 'last name' %>
			<%= f.email_field :email, placeholder: 'email address' %>
			<%= f.password_field :password, placeholder: 'password' %>
			<p><b>Are you part of a company or group?</b></p>
			<%= f.text_field :company, placeholder: 'type company here' %></br>
			<%= f.submit 'Join', class: 'btn btn-primary' %>

		<% end %></center>
	</div>
</div>

app/views/users/show.html.erb
<div class='row-fluid'>
	<div class='span6'>
		<h1>My Tasks</a></h1>
		<%= link_to 'add a task', new_task_url, class: 'btn btn-success'  %></br></br>
		<div>
			<table class='table table-striped table-hover well'>
				<th></th><th>Task Name</th><th>Description</th>
				<% @tasks.each do |task| %>
					<%= render 'task_partial', task: task %>
				<% end %>
			</table>
		</div>

	</div>

	<div class='span3'>
		<h1>My Teams</a></h1>
		<%= link_to 'make a new team', new_team_url, class: 'btn btn-success'  %></br></br>
		<div>
			<table class='table table-striped table-hover well'>
				<th>Team Name</th>
				<tbody>
				<% @teams.each do |team| %>
					<tr>
						<td><%= team.name %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>

	</div>
	<div class='span3'>
		<h1>My Projects</a></h1>
		<%= link_to 'start a new project', new_project_url, class: 'btn btn-success'  %></br></br>
		<div>
			<table class='table table-striped table-hover well'>
				<th></th><th>Project Name</th>
				<% @projects.each do |project| %>
					<%= render 'project_partial', project: project %>
				<% end %>
			</table>
		</div>

	</div>
</div>